apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-service
  namespace: staging-deployment
  labels:
    run: account-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: account-service
    spec:
      containers:
      - name: account-service
        image: 353258999787.dkr.ecr.us-east-1.amazonaws.com/account_service_microservice:latest
        ports:
        - containerPort: 2222
          protocol: TCP
      - name: mongo
        image: library/mongo
        ports:
        - containerPort: 27017
          protocol: TCP	
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: staging-deployment
spec:
  selector:
    run: account-service
  ports:
    - name: port1
      protocol: TCP
      port: 2222
      targetPort: 2222
    - name: port2
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: NodePort

